python3 firstcut.py \
  --source en \
  --target de \
  --infn ../trialdata/en-de.trial.xml \
  --outfn ./theoutput \
  --lm /space/trykenlm/kenlm/europarl.binary \
  --weights ./SAMPLE.weights \
  --zmert True \
  #--lm /space/german-wikipedia/german.lm \
