all: part00 part01 part02 part03 part04 part05 part06 part07 part08 part09 part10 part11 part12 part13 part14 part15 part16 part17 part18 part19 part20 part21 part22 part23 part24 part25 part26 part27 part28 part29 part30 part31 part32 part33 part34 part35 part36 part37 part38 part39 part40 part41 part42 part43 part44 part45 part46 part47 part48 part49 part50 part51 part52 part53 part54 part55 part56 part57 part58 part59 part60 part61 part62 part63 part64 part65 part66 part67 part68 part69 part70 part71 part72 part73 part74 part75 part76 part77 part78 part79 part80 part81 part82 part83 part84 part85 part86 part87 part88 part89 part90 part91 part92 part93 part94 part95 part96 part97 part98

part00:
	python3 separate.py arcs.00-of-99 > SEPARATED-arcs.00-of-99
part01:
	python3 separate.py arcs.01-of-99 > SEPARATED-arcs.01-of-99
part02:
	python3 separate.py arcs.02-of-99 > SEPARATED-arcs.02-of-99
part03:
	python3 separate.py arcs.03-of-99 > SEPARATED-arcs.03-of-99
part04:
	python3 separate.py arcs.04-of-99 > SEPARATED-arcs.04-of-99
part05:
	python3 separate.py arcs.05-of-99 > SEPARATED-arcs.05-of-99
part06:
	python3 separate.py arcs.06-of-99 > SEPARATED-arcs.06-of-99
part07:
	python3 separate.py arcs.07-of-99 > SEPARATED-arcs.07-of-99
part08:
	python3 separate.py arcs.08-of-99 > SEPARATED-arcs.08-of-99
part09:
	python3 separate.py arcs.09-of-99 > SEPARATED-arcs.09-of-99
part10:
	python3 separate.py arcs.10-of-99 > SEPARATED-arcs.10-of-99
part11:
	python3 separate.py arcs.11-of-99 > SEPARATED-arcs.11-of-99
part12:
	python3 separate.py arcs.12-of-99 > SEPARATED-arcs.12-of-99
part13:
	python3 separate.py arcs.13-of-99 > SEPARATED-arcs.13-of-99
part14:
	python3 separate.py arcs.14-of-99 > SEPARATED-arcs.14-of-99
part15:
	python3 separate.py arcs.15-of-99 > SEPARATED-arcs.15-of-99
part16:
	python3 separate.py arcs.16-of-99 > SEPARATED-arcs.16-of-99
part17:
	python3 separate.py arcs.17-of-99 > SEPARATED-arcs.17-of-99
part18:
	python3 separate.py arcs.18-of-99 > SEPARATED-arcs.18-of-99
part19:
	python3 separate.py arcs.19-of-99 > SEPARATED-arcs.19-of-99
part20:
	python3 separate.py arcs.20-of-99 > SEPARATED-arcs.20-of-99
part21:
	python3 separate.py arcs.21-of-99 > SEPARATED-arcs.21-of-99
part22:
	python3 separate.py arcs.22-of-99 > SEPARATED-arcs.22-of-99
part23:
	python3 separate.py arcs.23-of-99 > SEPARATED-arcs.23-of-99
part24:
	python3 separate.py arcs.24-of-99 > SEPARATED-arcs.24-of-99
part25:
	python3 separate.py arcs.25-of-99 > SEPARATED-arcs.25-of-99
part26:
	python3 separate.py arcs.26-of-99 > SEPARATED-arcs.26-of-99
part27:
	python3 separate.py arcs.27-of-99 > SEPARATED-arcs.27-of-99
part28:
	python3 separate.py arcs.28-of-99 > SEPARATED-arcs.28-of-99
part29:
	python3 separate.py arcs.29-of-99 > SEPARATED-arcs.29-of-99
part30:
	python3 separate.py arcs.30-of-99 > SEPARATED-arcs.30-of-99
part31:
	python3 separate.py arcs.31-of-99 > SEPARATED-arcs.31-of-99
part32:
	python3 separate.py arcs.32-of-99 > SEPARATED-arcs.32-of-99
part33:
	python3 separate.py arcs.33-of-99 > SEPARATED-arcs.33-of-99
part34:
	python3 separate.py arcs.34-of-99 > SEPARATED-arcs.34-of-99
part35:
	python3 separate.py arcs.35-of-99 > SEPARATED-arcs.35-of-99
part36:
	python3 separate.py arcs.36-of-99 > SEPARATED-arcs.36-of-99
part37:
	python3 separate.py arcs.37-of-99 > SEPARATED-arcs.37-of-99
part38:
	python3 separate.py arcs.38-of-99 > SEPARATED-arcs.38-of-99
part39:
	python3 separate.py arcs.39-of-99 > SEPARATED-arcs.39-of-99
part40:
	python3 separate.py arcs.40-of-99 > SEPARATED-arcs.40-of-99
part41:
	python3 separate.py arcs.41-of-99 > SEPARATED-arcs.41-of-99
part42:
	python3 separate.py arcs.42-of-99 > SEPARATED-arcs.42-of-99
part43:
	python3 separate.py arcs.43-of-99 > SEPARATED-arcs.43-of-99
part44:
	python3 separate.py arcs.44-of-99 > SEPARATED-arcs.44-of-99
part45:
	python3 separate.py arcs.45-of-99 > SEPARATED-arcs.45-of-99
part46:
	python3 separate.py arcs.46-of-99 > SEPARATED-arcs.46-of-99
part47:
	python3 separate.py arcs.47-of-99 > SEPARATED-arcs.47-of-99
part48:
	python3 separate.py arcs.48-of-99 > SEPARATED-arcs.48-of-99
part49:
	python3 separate.py arcs.49-of-99 > SEPARATED-arcs.49-of-99
part50:
	python3 separate.py arcs.50-of-99 > SEPARATED-arcs.50-of-99
part51:
	python3 separate.py arcs.51-of-99 > SEPARATED-arcs.51-of-99
part52:
	python3 separate.py arcs.52-of-99 > SEPARATED-arcs.52-of-99
part53:
	python3 separate.py arcs.53-of-99 > SEPARATED-arcs.53-of-99
part54:
	python3 separate.py arcs.54-of-99 > SEPARATED-arcs.54-of-99
part55:
	python3 separate.py arcs.55-of-99 > SEPARATED-arcs.55-of-99
part56:
	python3 separate.py arcs.56-of-99 > SEPARATED-arcs.56-of-99
part57:
	python3 separate.py arcs.57-of-99 > SEPARATED-arcs.57-of-99
part58:
	python3 separate.py arcs.58-of-99 > SEPARATED-arcs.58-of-99
part59:
	python3 separate.py arcs.59-of-99 > SEPARATED-arcs.59-of-99
part60:
	python3 separate.py arcs.60-of-99 > SEPARATED-arcs.60-of-99
part61:
	python3 separate.py arcs.61-of-99 > SEPARATED-arcs.61-of-99
part62:
	python3 separate.py arcs.62-of-99 > SEPARATED-arcs.62-of-99
part63:
	python3 separate.py arcs.63-of-99 > SEPARATED-arcs.63-of-99
part64:
	python3 separate.py arcs.64-of-99 > SEPARATED-arcs.64-of-99
part65:
	python3 separate.py arcs.65-of-99 > SEPARATED-arcs.65-of-99
part66:
	python3 separate.py arcs.66-of-99 > SEPARATED-arcs.66-of-99
part67:
	python3 separate.py arcs.67-of-99 > SEPARATED-arcs.67-of-99
part68:
	python3 separate.py arcs.68-of-99 > SEPARATED-arcs.68-of-99
part69:
	python3 separate.py arcs.69-of-99 > SEPARATED-arcs.69-of-99
part70:
	python3 separate.py arcs.70-of-99 > SEPARATED-arcs.70-of-99
part71:
	python3 separate.py arcs.71-of-99 > SEPARATED-arcs.71-of-99
part72:
	python3 separate.py arcs.72-of-99 > SEPARATED-arcs.72-of-99
part73:
	python3 separate.py arcs.73-of-99 > SEPARATED-arcs.73-of-99
part74:
	python3 separate.py arcs.74-of-99 > SEPARATED-arcs.74-of-99
part75:
	python3 separate.py arcs.75-of-99 > SEPARATED-arcs.75-of-99
part76:
	python3 separate.py arcs.76-of-99 > SEPARATED-arcs.76-of-99
part77:
	python3 separate.py arcs.77-of-99 > SEPARATED-arcs.77-of-99
part78:
	python3 separate.py arcs.78-of-99 > SEPARATED-arcs.78-of-99
part79:
	python3 separate.py arcs.79-of-99 > SEPARATED-arcs.79-of-99
part80:
	python3 separate.py arcs.80-of-99 > SEPARATED-arcs.80-of-99
part81:
	python3 separate.py arcs.81-of-99 > SEPARATED-arcs.81-of-99
part82:
	python3 separate.py arcs.82-of-99 > SEPARATED-arcs.82-of-99
part83:
	python3 separate.py arcs.83-of-99 > SEPARATED-arcs.83-of-99
part84:
	python3 separate.py arcs.84-of-99 > SEPARATED-arcs.84-of-99
part85:
	python3 separate.py arcs.85-of-99 > SEPARATED-arcs.85-of-99
part86:
	python3 separate.py arcs.86-of-99 > SEPARATED-arcs.86-of-99
part87:
	python3 separate.py arcs.87-of-99 > SEPARATED-arcs.87-of-99
part88:
	python3 separate.py arcs.88-of-99 > SEPARATED-arcs.88-of-99
part89:
	python3 separate.py arcs.89-of-99 > SEPARATED-arcs.89-of-99
part90:
	python3 separate.py arcs.90-of-99 > SEPARATED-arcs.90-of-99
part91:
	python3 separate.py arcs.91-of-99 > SEPARATED-arcs.91-of-99
part92:
	python3 separate.py arcs.92-of-99 > SEPARATED-arcs.92-of-99
part93:
	python3 separate.py arcs.93-of-99 > SEPARATED-arcs.93-of-99
part94:
	python3 separate.py arcs.94-of-99 > SEPARATED-arcs.94-of-99
part95:
	python3 separate.py arcs.95-of-99 > SEPARATED-arcs.95-of-99
part96:
	python3 separate.py arcs.96-of-99 > SEPARATED-arcs.96-of-99
part97:
	python3 separate.py arcs.97-of-99 > SEPARATED-arcs.97-of-99
part98:
	python3 separate.py arcs.98-of-99 > SEPARATED-arcs.98-of-99
